name: Android Test

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-version: '29.0.3'
        api-level: 29

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: List directory contents
      run: ls -al

    - name: List Gradle wrapper directory contents
      run: ls -al gradle/wrapper

    - name: Verify Gradle wrapper
      run: ./gradlew --version

    - name: Run tests
      run: ./gradlew testDebugUnitTest
